# Generated by Django 4.1.3 on 2023-01-31 18:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Datalake",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("logical_date", models.DateField()),
                ("batch_id", models.TextField()),
                ("src_alias", models.TextField()),
                ("src_url", models.TextField()),
                ("file", models.TextField()),
                ("data", models.JSONField()),
                ("data_normalized", models.JSONField()),
            ],
            options={
                "db_table": "datalake",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Datasource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField(unique=True)),
                ("slug", models.SlugField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                ("slug", models.SlugField(blank=True, default="")),
                (
                    "selected_columns",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="matching.datasource"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Matching",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("logical_date", models.DateField()),
                ("left_row_natural_id", models.TextField()),
                ("left_row_data", models.JSONField()),
                ("right_row_natural_id", models.TextField(null=True)),
                ("right_row_data", models.JSONField(null=True)),
                ("skipped", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "left_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="left_matchings",
                        to="matching.stream",
                    ),
                ),
                (
                    "right_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="right_matchings",
                        to="matching.stream",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
