# Generated by Django 4.1.3 on 2023-02-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matching",
            name="no_matching_row",
            field=models.BooleanField(default=False),
        ),
    ]
