-- https://docs.google.com/spreadsheets/d/1E_ya2wjJO9fvWbnngMcs9-FKshkzpgDrAkUSKslG3X4

SELECT
    x.code  AS "code",
    x.label AS "label"
FROM (
    VALUES
    (1, 'Premiers contacts'),
    (2, 'Démarches complémentaires'),
    (3, 'Appui Juridique'),
    (4, 'Comprendre la situation de mon proche'),
    (5, 'Soutien'),
    (6, 'Finances et patrimoine'),
    (7, 'Aides à domicile'),
    (8, 'Portage de repas'),
    (9, 'Relais au domicile'),
    (10, 'Accompagnement à l’autonomie'),
    (11, 'Soins à domicile'),
    (12, 'Points d’information'),
    (13, 'Diagnostic et adaptation du logement'),
    (14, 'Equipement'),
    (15, 'Téléassistance'),
    (16, 'Services de transports'),
    (17, 'Accompagnement aux déplacements'),
    (18, 'Achat, location et adaptation de véhicule'),
    (19, 'Formation à la conduite'),
    (20, 'Lieux de diagnostic'),
    (21, 'Rééducation et suivi thérapeutique'),
    (23, 'Prévention santé'),
    (24, 'Soins palliatifs'),
    (25, 'Soutien moral'),
    (26, 'Formation de l’aidant'),
    (27, 'Bien-être'),
    (28, 'Organisateurs de séjour'),
    (29, 'Lieux de séjour / vacances'),
    (30, 'Convivialité'),
    (31, 'Activités physiques'),
    (32, 'Activités culturelles et artistiques'),
    (34, 'Activités de bien-être'),
    (35, 'Etablissements pour personnes en situation de handicap'),
    (36, 'Habitats alternatifs'),
    (37, 'Résidences pour personnes âgées autonomes'),
    (38, 'Résidences pour personnes âgées dépendantes'),
    (39, 'Points d’information sur le répit'),
    (40, 'Relais au domicile'),
    (41, 'Relais hors du domicile'),
    (42, 'Crèches, assistantes maternelles'),
    (43, 'Accueils de loisirs et péri-scolaires'),
    (44, 'Baby-sitting'),
    (45, 'Scolarisation à l’école ordinaire'),
    (46, 'Scolarisation en établissements spécialisés'),
    (48, 'Aide aux étudiants'),
    (49, 'Formations, insertion professionnelle'),
    (50, 'Secteur protégé ou adapté'),
    (51, 'Soins à domicile')
) AS x (code, label)
