services:
  airflow-db:
    image: postgres:18
    restart: always
    healthcheck:
      test: pg_isready
      interval: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      - PGUSER=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow

  playwright:
    # the version should match the tasks requirements
    image: mcr.microsoft.com/playwright:v1.55.0-noble
    command: npx -y playwright@1.55.0 run-server --port 3000 --host 0.0.0.0
    user: pwuser
    init: true
    ipc: host

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    command: server /data
    restart: no
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_CONSOLE_ADDRESS=:9001
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data

  minio-init:
    image: minio/mc:RELEASE.2025-07-21T05-28-08Z
    entrypoint: /bin/bash -c
    command:
      - |
        mc alias set tmp http://minio:9000 minioadmin minioadmin
        mc admin update --yes tmp
        mc mb --ignore-existing tmp/data-inclusion-lake
    depends_on:
      - minio

  datawarehouse:
    image: data-inclusion/datawarehouse
    build: datawarehouse
    restart: no
    command: -c fsync=off -c full_page_writes=off -c synchronous_commit=off -c log_statement=all
    healthcheck:
      test: pg_isready
      interval: 5s
      retries: 5
    ports:
      - ${TARGET_POSTGRES_PORT:-5433}:5432
    environment:
      - PGUSER=data-inclusion
      - POSTGRES_DB=data-inclusion
      - POSTGRES_USER=data-inclusion
      - POSTGRES_PASSWORD=data-inclusion
      - BREVO_API_KEY=${AIRFLOW_VAR_BREVO_API_KEY}
    volumes:
      - pg-data:/var/lib/postgresql

  api:
    image: data-inclusion/api
    build: api
    depends_on:
      datawarehouse:
        condition: service_healthy
    restart: no
    ports:
      - ${API_PORT:-8000}:8000
    environment:
      - ENV=${API_ENV:-dev}
      - DEBUG=${API_DEBUG:-False}
      - DATABASE_URL=postgresql://data-inclusion:data-inclusion@datawarehouse:5432/data-inclusion
      - BASE_URL=http://127.0.0.1:8000
      - SECRET_KEY=USE_IN_DEVELOPMENT_ONLY
      - DATALAKE_ENDPOINT_URL=http://minio:9000
      - DATALAKE_BUCKET_NAME=data-inclusion-lake
      - DATALAKE_SECRET_KEY=minioadmin
      - DATALAKE_ACCESS_KEY=minioadmin

volumes:
  pg-data:
  minio-data:

networks:
  default:
    name: data-inclusion
