# Generated by Django 4.1.3 on 2022-12-02 16:00

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="Permanence",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("siret", models.TextField(db_index=True, null=True)),
                ("name", models.TextField()),
                ("address", models.TextField()),
                ("city", models.TextField()),
                ("postal_code", models.TextField()),
                ("position", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AddIndex(
            model_name="permanence",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="cnfs_name_trgm_idx", opclasses=("gin_trgm_ops",)
            ),
        ),
        migrations.AddIndex(
            model_name="permanence",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["address"], name="cnfs_address_trgm_idx", opclasses=("gin_trgm_ops",)
            ),
        ),
    ]
