from unittest.mock import ANY

import pytest

from data_inclusion.processings import geocode

pytestmark = pytest.mark.ban_api


@pytest.mark.parametrize(
    ("adresse", "expected"),
    [
        (
            {
                "id": "1",
                "adresse": "17 rue Malus",
                "code_postal": "59000",
                "code_insee": "59350",
                "commune": "Lille",
            },
            {
                "id": "1",
                "adresse": "17 rue Malus",
                "adresse_original": "17 rue Malus",
                "code_postal": "59000",
                "code_insee": "59350",
                "commune": "Lille",
                "commune_original": "Lille",
                "latitude": ANY,
                "longitude": ANY,
                "result_label": "17 Rue Malus 59000 Lille",
                "result_score": ANY,
                "result_score_next": None,
                "result_type": "housenumber",
                "result_id": "59350_5835_00017",
                "result_housenumber": "17",
                "result_name": "17 Rue Malus",
                "result_street": "Rue Malus",
                "result_postcode": "59000",
                "result_city": "Lille",
                "result_context": "59, Nord, Hauts-de-France",
                "result_citycode": "59350",
                "result_oldcitycode": "59350",
                "result_oldcity": "Lille",
                "result_district": None,
                "result_status": "ok",
            },
        ),
        (
            {
                "id": "2",
                "adresse": None,
                "code_postal": None,
                "code_insee": None,
                "commune": None,
            },
            None,
        ),
        (
            {
                "id": "1",
                "adresse": "bla",
                "code_postal": None,
                "code_insee": 38009,
                "commune": 'Anjou',
            },
            None
        ),
        (
            {
                "id": "1",
                "adresse": "",
                "code_postal": None,
                "code_insee": 38009,
                "commune": 'Anjou',
            },
            {
                "id": "1",
                "adresse": None,
                "adresse_original": None,
                "code_postal": None,
                "code_insee": "38009",
                "commune": "Anjou",
                "commune_original": "Anjou",
                "latitude": ANY,
                "longitude": ANY,
                "result_label": "Anjou",
                "result_score": ANY,
                "result_score_next": ANY,
                "result_type": "municipality",
                "result_id": "38009",
                "result_housenumber": None,
                "result_name": "Anjou",
                "result_street": None,
                "result_postcode": "38150",
                "result_city": "Anjou",
                "result_context": "38, Isère, Auvergne-Rhône-Alpes",
                "result_citycode": "38009",
                "result_oldcitycode": None,
                "result_oldcity": None,
                "result_district": None,
                "result_status": "ok",
            },
        ),
        (
            {
                "id": "1",
                "adresse": "bourg",
                "code_postal": None,
                "code_insee": 38009,
                "commune": 'Anjou',
            },
            {
                "id": "1",
                "adresse": "bourg",
                "adresse_original": "bourg",
                "code_postal": None,
                "code_insee": "38009",
                "commune": "Anjou",
                "commune_original": "Anjou",
                "latitude": ANY,
                "longitude": ANY,
                "result_label": "Anjou",
                "result_score": ANY,
                "result_score_next": ANY,
                "result_type": "municipality",
                "result_id": "38009",
                "result_housenumber": None,
                "result_name": "Anjou",
                "result_street": None,
                "result_postcode": "38150",
                "result_city": "Anjou",
                "result_context": "38, Isère, Auvergne-Rhône-Alpes",
                "result_citycode": "38009",
                "result_oldcitycode": None,
                "result_oldcity": None,
                "result_district": None,
                "result_status": "ok",
            },
        ),
        # Flaky tests. Ban api is not consistent
        # But the api send ok results, our code should behave like this.
        # (
        #     {
        #         "id": "1",
        #         "adresse": "anjou 07300",
        #         "code_postal": None,
        #         "code_insee": 38009,
        #         "commune": 'Anjou',
        #     },
        #     {
        #         "id": "1",
        #         "adresse": "anjou 07300",
        #         "adresse_original": "anjou 07300",
        #         "code_postal": None,
        #         "code_insee": "38009",
        #         "commune": "Anjou",
        #         "commune_original": "Anjou",
        #         "latitude": ANY,
        #         "longitude": ANY,
        #         "result_label": "Anjou",
        #         "result_score": ANY,
        #         "result_score_next": ANY,
        #         "result_type": "municipality",
        #         "result_id": "38009",
        #         "result_housenumber": None,
        #         "result_name": "Anjou",
        #         "result_street": None,
        #         "result_postcode": "38150",
        #         "result_city": "Anjou",
        #         "result_context": "38, Isère, Auvergne-Rhône-Alpes",
        #         "result_citycode": "38009",
        #         "result_oldcitycode": None,
        #         "result_oldcity": None,
        #         "result_district": None,
        #         "result_status": "ok",
        #     },
        # ),
        # (
        #     {
        #         "id": "1",
        #         "adresse": "Anjou",
        #         "code_postal": None,
        #         "code_insee": 38009,
        #         "commune": 'anjou 07300',
        #     },
        #     {
        #         "id": "1",
        #         "adresse": "Anjou",
        #         "adresse_original": "Anjou",
        #         "code_postal": None,
        #         "code_insee": "38009",
        #         "commune": "anjou 07300",
        #         "commune_original": "anjou 07300",
        #         "latitude": ANY,
        #         "longitude": ANY,
        #         "result_label": "Anjou",
        #         "result_score": ANY,
        #         "result_score_next": ANY,
        #         "result_type": "municipality",
        #         "result_id": "38009",
        #         "result_housenumber": None,
        #         "result_name": "Anjou",
        #         "result_street": None,
        #         "result_postcode": "38150",
        #         "result_city": "Anjou",
        #         "result_context": "38, Isère, Auvergne-Rhône-Alpes",
        #         "result_citycode": "38009",
        #         "result_oldcitycode": None,
        #         "result_oldcity": None,
        #         "result_district": None,
        #         "result_status": "ok",
        #     },
        # ),
        (
            {
                "id": "1",
                "adresse": "17 rue Malus",
                "code_postal": "59000",
                "code_insee": "59350",
                "commune": "Lille cedex 12345",
            },
            {
                "id": "1",
                "adresse": "17 rue Malus",
                "adresse_original": "17 rue Malus",
                "code_postal": None,
                "code_insee": "59350",
                "commune": "Lille",
                "commune_original": "Lille cedex 12345",
                "latitude": ANY,
                "longitude": ANY,
                "result_label": "17 Rue Malus 59000 Lille",
                "result_score": ANY,
                "result_score_next": None,
                "result_type": "housenumber",
                "result_id": "59350_5835_00017",
                "result_housenumber": "17",
                "result_name": "17 Rue Malus",
                "result_street": "Rue Malus",
                "result_postcode": "59000",
                "result_city": "Lille",
                "result_context": "59, Nord, Hauts-de-France",
                "result_citycode": "59350",
                "result_oldcitycode": "59350",
                "result_oldcity": "Lille",
                "result_district": None,
                "result_status": "ok",
            },
        ),
        (
            {
                "id": "1",
                "adresse": "17 rue Malus BP 12345",
                "code_postal": "59000",
                "code_insee": "59350",
                "commune": "Lille",
            },
            {
                "id": "1",
                "adresse": "17 rue Malus",
                "adresse_original": "17 rue Malus BP 12345",
                "code_postal": None,
                "code_insee": "59350",
                "commune": "Lille",
                "commune_original": "Lille",
                "latitude": ANY,
                "longitude": ANY,
                "result_label": "17 Rue Malus 59000 Lille",
                "result_score": ANY,
                "result_score_next": None,
                "result_type": "housenumber",
                "result_id": "59350_5835_00017",
                "result_housenumber": "17",
                "result_name": "17 Rue Malus",
                "result_street": "Rue Malus",
                "result_postcode": "59000",
                "result_city": "Lille",
                "result_context": "59, Nord, Hauts-de-France",
                "result_citycode": "59350",
                "result_oldcitycode": "59350",
                "result_oldcity": "Lille",
                "result_district": None,
                "result_status": "ok",
            },
        ),
        (
            {
                "id": "1",
                "adresse": "17 rue Malus",
                "code_postal": "59000",
                "code_insee": "59350",
                "commune": None,
            },
            {
                "id": "1",
                "adresse": "17 rue Malus",
                "adresse_original": "17 rue Malus",
                "code_postal": "59000",
                "code_insee": "59350",
                "commune": None,
                "commune_original": None,
                "latitude": ANY,
                "longitude": ANY,
                "result_label": "17 Rue Malus 59000 Lille",
                "result_score": ANY,
                "result_score_next": None,
                "result_type": "housenumber",
                "result_id": "59350_5835_00017",
                "result_housenumber": "17",
                "result_name": "17 Rue Malus",
                "result_street": "Rue Malus",
                "result_postcode": "59000",
                "result_city": "Lille",
                "result_context": "59, Nord, Hauts-de-France",
                "result_citycode": "59350",
                "result_oldcitycode": "59350",
                "result_oldcity": "Lille",
                "result_district": None,
                "result_status": "ok",
            },
        ),
    ],
)
def test_ban_geocode(adresse: dict, expected: dict):
    result_df = geocode(data=adresse)

    assert result_df == ([expected] if expected is not None else [])


@pytest.mark.parametrize(
    ("raw", "cleaned"),
    [
        (
            {
                "id": "1",
                "adresse": "3 route de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye CEDEX 88793",
            },
            {
                "id": "1",
                "adresse": "3 route de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
        ),
        (
            {
                "id": "1",
                "adresse": "3 route de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye cedex 88793",
            },
            {
                "id": "1",
                "adresse": "3 route de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
        ),
        (
            {
                "id": "1",
                "adresse": "3 route de Cobonne bp 7872387",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
            {
                "id": "1",
                "adresse": "3 route de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
        ),
        (
            {
                "id": "1",
                "adresse": "3 route de Cobonne CS 23123",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
            {
                "id": "1",
                "adresse": "3 route de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
        ),
        (
            {
                "id": "1",
                "adresse": "3 rte de avenue de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
            {
                "id": "1",
                "adresse": "3 route de avenue de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
        ),
        (
            {
                "id": "1",
                "adresse": "3 Rte de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
            {
                "id": "1",
                "adresse": "3 route de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
        ),
        (
            {
                "id": "1",
                "adresse": "3 RTE de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
            {
                "id": "1",
                "adresse": "3 route de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
        ),
        (
            {
                "id": "1",
                "adresse": "CS 23123 3 route de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
            {
                "id": "1",
                "adresse": "3 route de Cobonne",
                "code_postal": "26400",
                "code_insee": "26011",
                "commune": "Aouste-sur-Sye",
            },
        ),
        (
            {
                "id": "1",
                "adresse": "3 rue d'allemagne",
                "code_postal": "69780",
                "code_insee": "69283",
                "commune": "Mions",
            },
            {
                "id": "1",
                "adresse": "3 rue d'allemagne",
                "code_postal": "69780",
                "code_insee": "69283",
                "commune": "Mions",
            },
        )
    ],
)
def test_ban_cleaning_cedex(raw: dict, cleaned: dict):
    result_df_raw = geocode(data=raw)
    result_df_cleaned = geocode(data=cleaned)


    assert result_df_cleaned[0]["adresse"] == result_df_raw[0]['adresse']
    assert result_df_cleaned[0]["commune"] == result_df_raw[0]['commune']
    assert result_df_raw[0]['result_status'] == 'ok'
    assert result_df_cleaned[0]['result_status'] == 'ok'
    assert result_df_raw[0]['result_score'] <= result_df_cleaned[0]['result_score']
