{{ config(materialized='ephemeral') }}
SELECT
    x.code,
    x.label
FROM (
    VALUES
    -- noqa: disable=layout.spacing
    ('abortion',                              'Avortement'),
    ('access_to_housing',                     'Conseil logement'),
    ('accomodation_and_housing',              'Hébergement et logement'),
    ('activities',                            'Activités'),
    ('acupuncture',                           'Acupuncture'),
    ('addiction_care',                        'Prise en charge des addictions'),
    ('addiction_prevention_and_material',     'Prévention et matériel contre les addictions'),
    ('administrative_assistance',             'Conseil administratif'),
    ('affective_life',                        'Vie affective'),
    ('allergology',                           'Allergologie'),
    ('animal_assitance',                      'Animaux'),
    ('baby_parcel',                           'Colis bébé'),
    ('babysitting',                           'Garde d’enfants'),
    ('budget_advice',                         'Conseil budget'),
    ('cardiology',                            'Cardiologie'),
    ('carpooling',                            'Co-voiturage'),
    ('chauffeur_driven_transport',            'Transport avec chauffeur'),
    ('child_care',                            'Soins enfants'),
    ('chronic_diseases',                      'Maladies chroniques'),
    ('citizen_housing',                       'Hébergement citoyen'),
    ('clothing',                              'Vêtements'),
    ('community_garden',                      'Jardin solidaire'),
    ('computers_at_your_disposal',            'Ordinateur'),
    ('contraception',                         'Contraception'),
    ('cooking_workshop',                      'Atelier cuisine'),
    ('counseling',                            'Conseil'),
    ('day_hosting',                           'Accueil de jour'),
    ('dental_care',                           'Dentaire'),
    ('dermatology',                           'Dermatologie'),
    ('digital_safe',                          'Coffre-fort numérique'),
    ('digital_tools_training',                'Atelier numérique'),
    ('disability_advice',                     'Conseil handicap'),
    ('domiciliation',                         'Domiciliation'),
    ('driving_license',                       'Permis de conduire'),
    ('echography',                            'Échographie'),
    ('electrical_outlets_available',          'Prise'),
    ('emergency_accommodation',               'Hébergement d’urgence'),
    ('emergency_contraception',               'Contraception d’urgence'),
    ('endocrinology',                         'Endocrinologie'),
    ('equipment',                             'Matériel'),
    ('face_masks',                            'Masques'),
    ('family_area',                           'Espace famille'),
    ('find_healthcare',                       'Trouver des soins de santé'),
    ('food_distribution',                     'Distribution de repas'),
    ('food_packages',                         'Panier alimentaire'),
    ('food_voucher',                          'Bon / chèque alimentaire'),
    ('food',                                  'Alimentation'),
    ('fountain',                              'Fontaine à eau'),
    ('french_course',                         'Cours de français'),
    ('gastroenterology',                      'Gastro-entérologie'),
    ('general_practitioner',                  'Médecin généraliste'),
    ('gynecology',                            'Gynécologie'),
    ('hairdresser',                           'Coiffeur'),
    ('health_assessment',                     'Bilan de santé'),
    ('health_coverage',                       'Couverture santé'),
    ('health_specialists',                    'Spécialistes'),
    ('health',                                'Santé'),
    ('hearing_care',                          'Santé auditive'),
    ('hiv_prevention',                        'Prévention du VIH'),
    ('hygiene_and_wellness',                  'Hygiène et bien-être'),
    ('hygiene_products',                      'Produits d’hygiène'),
    ('infirmary',                             'Infirmerie'),
    ('information_point',                     'Point d’information et d’orientation'),
    ('integration_through_economic_activity', 'Insertion par l’activité économique'),
    ('job_coaching',                          'Accompagnement à l’emploi'),
    ('kinesitherapy',                         'Kinésithérapie'),
    ('laundry',                               'Laverie'),
    ('legal_advice',                          'Permanence juridique'),
    ('libraries',                             'Bibliothèque'),
    ('long_term_accomodation',                'Hébergement à long terme'),
    ('luggage_storage',                       'Bagagerie'),
    ('mammography',                           'Mammographie'),
    ('medical_accommodation',                 'Hébergement médical'),
    ('mental_health_education',               'Éducation à la santé mentale'),
    ('mobility_assistance',                   'Aide à la mobilité'),
    ('mobility_financing',                    'Aide financière pour la mobilité'),
    ('mobility_support',                      'Aide à la mobilité'),
    ('museums',                               'Musée'),
    ('nutrition',                             'Nutrition'),
    ('optical_care',                          'Soins optiques'),
    ('osteopathy',                            'Ostéopathe'),
    ('other_activities',                      'Activités diverses'),
    ('otorhinolaryngology',                   'Oto-rhino-laryngologie'),
    ('overnight_stop',                        'Halte de nuit'),
    ('parent_assistance',                     'Conseil aux parents'),
    ('pedicure',                              'Pédicure'),
    ('personal_vehicle_access',               'Accès à un véhicule personnel'),
    ('phlebology',                            'Phlébologie'),
    ('pneumology',                            'Pneumologie'),
    ('pregnancy_care',                        'Suivi grossesse'),
    ('psychiatry',                            'Psychiatrie'),
    ('psychological_support',                 'Psychologie'),
    ('public_writer',                         'Écrivain public'),
    ('radiology',                             'Radiologie'),
    ('rest_area',                             'Espace de repos'),
    ('rheumatology',                          'Rhumatologie'),
    ('seated_catering',                       'Restauration assise'),
    ('sexual_health_education',               'Éducation à la santé sexuelle'),
    ('sexual_health_vaccination',             'Vaccination en santé sexuelle'),
    ('sexual_violence_support',               'Soutien aux victimes de violences sexuelles'),
    ('shared_kitchen',                        'Cuisine partagée'),
    ('shower',                                'Douche'),
    ('social_accompaniment',                  'Accompagnement social'),
    ('social_grocery_stores',                 'Épicerie Sociale et Solidaire'),
    ('solidarity_fridge',                     'Frigo solidaire'),
    ('solidarity_store',                      'Boutique solidaire'),
    ('speech_therapy',                        'Orthophonie'),
    ('sport_activities',                      'Activités sportives'),
    ('std_testing',                           'Dépistage'),
    ('sti_prevention_testing',                'Prévention et dépistage IST'),
    ('stomatology',                           'Stomatologie'),
    ('support_groups',                        'Groupes de soutien'),
    ('technology',                            'Technologie'),
    ('telephone_at_your_disposal',            'Téléphone'),
    ('therapeutic_activities',                'Activités thérapeutiques'),
    ('toilets',                               'Toilettes'),
    ('training_and_jobs',                     'Formation et emploi'),
    ('transportation_mobility',               'Transport / Mobilité'),
    ('tutoring',                              'Soutien scolaire'),
    ('urology',                               'Urologie'),
    ('vaccination',                           'Vaccination'),
    ('vehicle_maintenance',                   'Entretien de véhicule'),
    ('vet_care',                              'Vétérinaire'),
    ('welcome',                               'Accueil'),
    ('wellness',                              'Bien-être'),
    ('wifi',                                  'Wifi')
    -- noqa: enable=layout.spacing
) AS x (code, label)
