-- the mapping is documented here:
-- https://apisolidarite.soliguide.fr/Documentation-technique-de-l-API-Solidarit-ecaf8198f0e9400d93140b8043c9f2ce

SELECT x.* FROM
    JSONB_EACH_TEXT(CAST($$
{
 "health": "Santé",
  "addiction": "Addiction",
  "std_testing": "Dépistage",
  "psychological_support": "Psychologie",
  "child_care": "Soins enfants",
  "general_practitioner": "Médecin généraliste",
  "dental_care": "Dentaire",
  "pregnancy_care": "Suivi grossesse",
  "vaccination": "Vaccination",
  "infirmary": "Infirmerie",
  "vet_care": "Vétérinaire",
  "health_specialists": "Spécialistes",
  "allergology": "Allergologie",
  "cardiology": "Cardiologie",
  "dermatology": "Dermatologie",
  "echography": "Échographie",
  "endocrinology": "Endocrinologie",
  "gastroenterology": "Gastro-entérologie",
  "gynecology": "Gynécologie",
  "kinesitherapy": "Kinésithérapie",
  "mammography": "Mammographie",
  "ophthalmology": "Ophtalmologie",
  "otorhinolaryngology": "Oto-rhino-laryngologie",
  "nutrition": "Nutrition",
  "pedicure": "Pédicure",
  "phlebology": "Phlébologie",
  "pneumology": "Pneumologie",
  "radiology": "Radiologie",
  "rheumatology": "Rhumatologie",
  "urology": "Urologie",
  "speech_therapy": "Orthophonie",
  "stomatology": "Stomatologie",
  "osteopathy": "Ostéopathe",
  "acupuncture": "Acupuncture",
  "mobility": "Transport / Mobilité",
  "carpooling": "Co-voiturage",
  "provision_of_vehicles": "Mise à disposition de véhicule",
  "chauffeur_driven_transport": "Transport avec chauffeur",
  "mobility_assistance": "Aide à la mobilité",
  "training_and_jobs": "Formation et emploi",
  "digital_tools_training": "Atelier numérique",
  "french_course": "Cours de français",
  "job_coaching": "Accompagnement à l'emploi",
  "integration_through_economic_activity": "Insertion par l'activité économique",
  "tutoring": "Soutien scolaire",
  "hygiene_and_wellness": "Hygiène et bien-être",
  "shower": "Douche",
  "laundry": "Laverie",
  "wellness": "Bien-être",
  "toilets": "Toilettes",
  "hygiene_products": "Produits d'hygiène",
  "face_masks": "Masques",
  "counseling": "Conseil",
  "legal_advice": "Permanence juridique",
  "domiciliation": "Domiciliation",
  "social_accompaniment": "Accompagnement social",
  "public_writer": "Écrivain public",
  "disability_advice": "Conseil handicap",
  "administrative_assistance": "Conseil administratif",
  "parent_assistance": "Conseil aux parents",
  "budget_advice": "Conseil budget",
  "technology": "Technologie",
  "computers_at_your_disposal": "Ordinateur",
  "wifi": "Wifi",
  "electrical_outlets_available": "Prise",
  "telephone_at_your_disposal": "Téléphone",
  "digital_safe": "Coffre-fort numérique",
  "food": "Alimentation",
  "food_distribution": "Distribution de repas",
  "seated_catering": "Restauration assise",
  "food_packages": "Panier alimentaire",
  "social_grocery_stores": "Épicerie Sociale et Solidaire",
  "fountain": "Fontaine à eau",
  "solidarity_fridge": "Frigo solidaire",
  "shared_kitchen": "Cuisine partagée",
  "cooking_workshop": "Atelier cuisine",
  "baby_parcel": "Colis bébé",
  "food_voucher": "Bon / chèque alimentaire",
  "community_garden": "Jardin solidaire",
  "welcome": "Accueil",
  "day_hosting": "Accueil de jour",
  "rest_area": "Espace de repos",
  "babysitting": "Garde d'enfants",
  "family_area": "Espace famille",
  "information_point": "Point d'information et d'orientation",
  "activities": "Activités",
  "sport_activities": "Activités sportives",
  "museums": "Musée",
  "libraries": "Bibliothèque",
  "other_activities": "Activités diverses",
  "equipment": "Matériel",
  "luggage_storage": "Bagagerie",
  "solidarity_store": "Boutique solidaire",
  "clothing": "Vêtements",
  "animal_assitance": "Animaux",
  "accomodation_and_housing": "Hébergement et logement",
  "overnight_stop": "Halte de nuit",
  "emergency_accommodation": "Hébergement d'urgence",
  "long_term_accomodation": "Hébergement à long terme",
  "citizen_housing": "Hébergement citoyen",
  "access_to_housing": "Conseil logement" 
}
$$ AS JSONB)) AS x (code, label)
