name: 'data_inclusion'
version: '1.0.0'
config-version: 2

profile: 'data_inclusion'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_inclusion:
    +sql_header: "SET LC_TIME='fr_FR.utf8';"

    staging:
      +schema: staging

      sources:
        +materialized: view

      decoupage_administratif:
        +materialized: table

    intermediate:
      +schema: "{{ 'intermediate_tmp' if var('build_intermediate_tmp', false) else 'intermediate' }}"
      +materialized: table

    marts:
      +schema: marts
      +contract:
        enforced: true

      inclusion:
        +materialized: table

      opendata:
        +schema: opendata
        +materialized: view
        +contract:
          enforced: false

data_tests:
  +store_failures: true

seeds:
  data_inclusion:
    schema:
      +schema: schema
      +full_refresh: true
      +column_types:
        value: text
        label: text
        description: text
      +post-hook:
        - "ALTER TABLE {{ this }} ADD UNIQUE (value)"
