name: "data-inclusion"

services:
  playwright:
    # the version should match the tasks requirements
    image: mcr.microsoft.com/playwright:v1.55.0-noble
    command: npx -y playwright@1.55.0 run-server --port 3000 --host 0.0.0.0
    user: pwuser
    init: true
    ipc: host
    depends_on:
      - airflow-scheduler

  datawarehouse:
    image: ghcr.io/gip-inclusion/data-inclusion-datawarehouse:${STACK_VERSION}
    shm_size: '128mb'
    restart: always
    healthcheck:
      test: pg_isready
      interval: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      - PGUSER=${DATAWAREHOUSE_DI_USERNAME}
      - POSTGRES_DB=${DATAWAREHOUSE_DI_DATABASE}
      - POSTGRES_USER=${DATAWAREHOUSE_DI_USERNAME}
      - POSTGRES_PASSWORD=${DATAWAREHOUSE_DI_PASSWORD}
      - BREVO_API_KEY=${AIRFLOW_VAR_BREVO_API_KEY}
    volumes:
      - datawarehouse-data:/var/lib/postgresql

  reverse-proxy:
    image: traefik:v3.6
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO=websecure
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
      - TRAEFIK_CERTIFICATESRESOLVERS_MAIN_ACME_TLSCHALLENGE=true
      - TRAEFIK_CERTIFICATESRESOLVERS_MAIN_ACME_EMAIL=tech@data.inclusion.beta.gouv.fr
      - TRAEFIK_CERTIFICATESRESOLVERS_MAIN_ACME_STORAGE=/letsencrypt/acme.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt-data:/letsencrypt

volumes:
  datawarehouse-data:
  letsencrypt-data:

networks:
  default:
    name: data-inclusion
