"""structure_thematique

Revision ID: 4f1203eaf6cf
Revises: d36ba9e88838
Create Date: 2022-08-18 18:17:12.258708

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "4f1203eaf6cf"
down_revision = "d36ba9e88838"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "structure",
        sa.Column("thematiques", postgresql.ARRAY(sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("structure", "thematiques")
    # ### end Alembic commands ###
