"""service

Revision ID: 848afea21c28
Revises: 4f1203eaf6cf
Create Date: 2022-08-24 16:17:38.898610

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "848afea21c28"
down_revision = "4f1203eaf6cf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service",
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("structure_index", sa.Integer(), nullable=True),
        sa.Column("nom", sa.Text(), nullable=True),
        sa.Column("presentation_resume", sa.Text(), nullable=True),
        sa.Column("types", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("thematiques", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("prise_rdv", sa.Text(), nullable=True),
        sa.Column("frais", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("frais_autres", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["structure_index"],
            ["structure.index"],
        ),
        sa.PrimaryKeyConstraint("index"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service")
    # ### end Alembic commands ###
