WITH categories AS (
    SELECT x.*
    FROM (
        VALUES
        -- Mapping: https://apisolidarite.soliguide.fr/Documentation-technique-de-l-API-Solidarit-ecaf8198f0e9400d93140b8043c9f2ce
        ('0', 'Unknowed'),
        ('100', 'Santé'),
        ('101', 'Addiction'),
        ('102', 'Dépistage'),
        ('103', 'Psychologie'),
        ('104', 'Soins enfants'),
        ('105', 'Médecin généraliste'),
        ('106', 'Dentaire'),
        ('107', 'Suivi grossesse'),
        ('108', 'Vaccination'),
        ('109', 'Infirmerie'),
        ('110', 'Vétérinaire'),
        ('200', 'Formation et emploi'),
        ('201', 'Atelier numérique'),
        ('202', 'Cours de français'),
        ('203', 'Accompagnement à l''emploi'),
        ('204', 'Insertion par l''activité économique'),
        ('205', 'Soutien scolaire'),
        ('300', 'Hygiène et bien-être'),
        ('301', 'Douche'),
        ('302', 'Laverie'),
        ('303', 'Bien-être'),
        ('304', 'Toilettes'),
        ('305', 'Produits d''hygiène'),
        ('306', 'Masques'),
        ('400', 'Conseil'),
        ('401', 'Permanence juridique'),
        ('402', 'Domiciliation'),
        ('403', 'Accompagnement social'),
        ('404', 'Écrivain public'),
        ('405', 'Conseil handicap'),
        ('406', 'Conseil administratif'),
        ('407', 'Conseil aux parents'),
        ('408', 'Conseil budget'),
        ('500', 'Technologie'),
        ('501', 'Ordinateur'),
        ('502', 'Wifi'),
        ('503', 'Prise'),
        ('504', 'Téléphone'),
        ('505', 'Coffre-fort numérique'),
        ('600', 'Alimentation'),
        ('601', 'Distribution de repas'),
        ('602', 'Restauration assise'),
        ('603', 'Colis Alimentaire'),
        ('604', 'Épicerie Sociale et Solidaire'),
        ('605', 'Fontaine à eau'),
        ('700', 'Accueil'),
        ('701', 'Accueil de jour'),
        ('702', 'Espace de repos'),
        ('703', 'Garde d''enfants'),
        ('704', 'Espace famille'),
        ('705', 'Point d''information'),
        ('800', 'Activités'),
        ('801', 'Activités sportives'),
        ('802', 'Musée'),
        ('803', 'Bibliothèque'),
        ('804', 'Activités diverses'),
        ('805', 'Animations et loisirs'),
        ('900', 'Matériel'),
        ('901', 'Bagagerie'),
        ('902', 'Boutique solidaire'),
        ('903', 'Vêtements'),
        ('904', 'Animaux'),
        ('1100', 'Spécialistes'),
        ('1101', 'Allergologie'),
        ('1102', 'Cardiologie'),
        ('1103', 'Dermatologie'),
        ('1104', 'Échographie'),
        ('1105', 'Endocrinologie'),
        ('1106', 'Gastro-entérologie'),
        ('1107', 'Gynécologie'),
        ('1108', 'Kinésithérapie'),
        ('1109', 'Mammographie'),
        ('1110', 'Ophtalmologie'),
        ('1111', 'Oto-rhino-laryngologie'),
        ('1112', 'Nutrition'),
        ('1113', 'Pédicure'),
        ('1114', 'Phlébologie'),
        ('1115', 'Pneumologie'),
        ('1116', 'Radiologie'),
        ('1117', 'Rhumatologie'),
        ('1118', 'Urologie'),
        ('1119', 'Orthophonie'),
        ('1120', 'Stomatologie'),
        ('1121', 'Ostéopathe'),
        ('1122', 'Accupuncture'),
        ('1200', 'Transport & mobilité'),
        ('1201', 'Co-voiturage'),
        ('1202', 'Mise à disposition de véhicule'),
        ('1203', 'Transport avec chauffeur'),
        ('1204', 'Aide à la mobilité'),
        ('1300', 'Hébergement & logement'),
        ('1301', 'Halte de nuit'),
        ('1302', 'Hébergement d''urgence'),
        ('1303', 'Hébergement à long terme'),
        ('1304', 'Hébergement citoyen'),
        ('1305', 'Conseil logement')
    ) AS x (code, label)
)

SELECT * FROM categories
