# Generated by Django 4.0.3 on 2022-03-30 14:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Structure",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("siret", models.CharField(db_index=True, max_length=14, unique=True)),
                ("code_safir_pe", models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ("name", models.CharField(max_length=255)),
                ("ape", models.CharField(max_length=6)),
                ("address1", models.CharField(blank=True, max_length=255)),
                ("address2", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("city_code", models.CharField(db_index=True, max_length=5)),
                ("postal_code", models.CharField(max_length=5)),
                ("is_siege", models.BooleanField()),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StructureTypology",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StructureReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("branch_id", models.CharField(blank=True, default="", max_length=5)),
                ("slug", models.SlugField(blank=True, default="")),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("short_desc", models.CharField(blank=True, default="", max_length=280)),
                ("url", models.URLField(blank=True, default="")),
                ("full_desc", models.TextField(blank=True, default="")),
                ("phone", models.TextField(blank=True, default="", max_length=10)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("postal_code", models.CharField(blank=True, default="", max_length=5)),
                ("city_code", models.CharField(blank=True, default="", max_length=5)),
                ("city", models.CharField(blank=True, default="", max_length=255)),
                ("department", models.CharField(blank=True, default="", max_length=3)),
                ("address1", models.CharField(blank=True, default="", max_length=255)),
                ("address2", models.CharField(blank=True, default="", max_length=255)),
                ("code_ape", models.CharField(blank=True, default="", max_length=6)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("geocoding_score", models.FloatField(blank=True, null=True)),
                ("source", models.TextField(blank=True, default="")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="inclusion.structurereport",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="inclusion.structure"
                    ),
                ),
                (
                    "typology",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="inclusion.structuretypology",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
