# Generated by Django 4.0.3 on 2022-04-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0004_structurereport_creation_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="structurereport",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
