# Generated by Django 4.0.3 on 2022-05-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0005_structurereport_extra"),
    ]

    operations = [
        migrations.RenameField(
            model_name="structurereport",
            old_name="address1",
            new_name="adresse",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="city_code",
            new_name="code_insee",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="postal_code",
            new_name="code_postal",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="city",
            new_name="commune",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="address2",
            new_name="complement_adresse",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="email",
            new_name="courriel",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="creation_date",
            new_name="date_creation",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="modification_date",
            new_name="date_maj",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="department",
            new_name="departement",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="branch_id",
            new_name="id_antenne",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="name",
            new_name="nom",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="full_desc",
            new_name="presentation_detail",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="short_desc",
            new_name="presentation_resume",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="geocoding_score",
            new_name="score_geocodage",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="url",
            new_name="site_web",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="parent",
            new_name="structure_mere",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="phone",
            new_name="telephone",
        ),
        migrations.RenameField(
            model_name="structurereport",
            old_name="typology",
            new_name="typologie",
        ),
    ]
