# Generated by Django 4.0.3 on 2022-05-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0006_francais"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structurereport",
            name="code_ape",
        ),
        migrations.RemoveField(
            model_name="structurereport",
            name="date_creation",
        ),
        migrations.RemoveField(
            model_name="structurereport",
            name="slug",
        ),
    ]
