# Generated by Django 4.0.3 on 2022-05-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0007_remove_structurereport_code_ape_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="rna",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="siret",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.CheckConstraint(
                check=models.Q(("rna__isnull", True), ("siret__isnull", True), _negated=True), name="has_pivot"
            ),
        ),
    ]
