# Generated by Django 4.0.3 on 2022-05-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0008_structure_rna_alter_structure_siret_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structure",
            name="address1",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="address2",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="ape",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="city",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="city_code",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="is_siege",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="name",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="postal_code",
        ),
    ]
