# Generated by Django 4.0.3 on 2022-05-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0010_remove_structure_code_safir_pe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structurereport",
            name="reporter",
        ),
    ]
