# Generated by Django 4.0.3 on 2022-05-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0011_remove_structurereport_reporter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structurereport",
            name="departement",
        ),
    ]
