# Generated by Django 4.0.3 on 2022-05-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0012_remove_structurereport_departement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structurereport",
            name="telephone",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
