# Generated by Django 4.0.3 on 2022-05-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0013_alter_structurereport_telephone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structurereport",
            name="id_antenne",
        ),
        migrations.RemoveField(
            model_name="structurereport",
            name="structure_mere",
        ),
        migrations.AddField(
            model_name="structurereport",
            name="id_in_source",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="structurereport",
            name="parent_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_reports",
                to="inclusion.structurereport",
            ),
        ),
        migrations.AddField(
            model_name="structurereport",
            name="rna",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="structurereport",
            name="siret",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="structurereport",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="inclusion.structure",
            ),
        ),
        migrations.AddConstraint(
            model_name="structurereport",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("parent_report__isnull", False), ("structure__isnull", True)),
                    models.Q(("parent_report__isnull", True), ("structure__isnull", False)),
                    _connector="OR",
                ),
                name="not_orphaned",
            ),
        ),
    ]
