# Generated by Django 4.0.3 on 2022-06-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0015_remove_structurereport_not_orphaned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="structurereport",
            name="lien_source",
            field=models.URLField(blank=True, default=""),
        ),
    ]
