# Generated by Django 4.0.3 on 2022-06-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0016_structurereport_lien_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="structurereport",
            name="is_latest",
            field=models.BooleanField(default=False),
        ),
    ]
