# Generated by Django 4.0.3 on 2022-06-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0017_structurereport_is_latest"),
    ]

    operations = [
        migrations.AddField(
            model_name="structurereport",
            name="horaires_ouverture",
            field=models.TextField(blank=True, default=""),
        ),
    ]
