# Generated by Django 4.0.6 on 2022-07-25 16:53

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inclusion", "0019_alter_structurereport_telephone"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructureLabel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="structurereport",
            name="accessibilite",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="structurereport",
            name="labels_autres",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name="structurereport",
            name="labels_nationaux",
            field=models.ManyToManyField(related_name="reports", to="inclusion.structurelabel"),
        ),
    ]
