from django.db import migrations

STRUCTURE_LABELS = [
    ("ACTION_LOGEMENT", "Action logement"),
    ("AFPA", "AFPA"),
    ("AGEFIPH", "AGEFIPH"),
    ("AIDANTS_CONNECT", "Aidants Connect"),
    ("ALLIANCE_VILLES_EMPLOI", "Alliance villes emploi"),
    ("ANLCI", "ANLCI"),
    ("APTIC", "APTIC"),
    ("BANQUES_ALIMENTAIRES", "Banques alimentaires"),
    ("CAF", "CAF"),
    ("CAMPUS_CONNECTE", "Campus connecté"),
    ("CCI", "CCI"),
    ("CHANTIER_ECOLE", "Chantier école"),
    ("CHEOPS", "Cheops"),
    ("COORACE", "Coorace"),
    ("CRESUS", "Crésus"),
    ("CROIX_ROUGE", "Croix rouge"),
    ("DIHAL", "DIHAL"),
    ("ECOLES_DE_LA_DEUXIEME_CHANCE", "Ecoles de la deuxième chance"),
    ("EMMAUS", "Emmaus"),
    ("ENVIE", "Envie"),
    ("EPIDE", "EPIDE"),
    ("FABRIQUE_DE_TERRITOIRE", "Fabrique de Territoire"),
    ("FEDERATION_DES_ACTEURS_DE_LA_SOLIDARITE", "Fédération des acteurs de la solidarité"),
    ("FEDERATION_DES_ENTREPRISES_DINSERTION", "Fédération des entreprises d'insertion"),
    ("FRANCE_SERVICE", "France service"),
    ("FRENCH_TECH", "French Tech"),
    ("GEIQ", "GEIQ"),
    ("GRANDES_ECOLES_DU_NUMERIQUE", "Grandes écoles du numérique"),
    ("INAE", "INAE"),
    ("LA_RESSOURCERIE", "La ressourcerie"),
    ("MAISONS_DE_LEMPLOI", "Maisons de l'Emploi"),
    ("MDPH", "MDPH"),
    ("MISSION_LOCALE", "Mission Locale"),
    ("MOBIN", "Mobin"),
    ("POINT_CONSEIL_BUDGET", "Point conseil budget"),
    ("POINT_JUSTICE", "Points Justice"),
    ("POLE_EMPLOI", "Pôle emploi"),
    ("RESSOURCERIES", "Ressourceries"),
    ("RESTOS_DU_COEUR", "Restos du coeur"),
    ("SECOURS_POPULAIRE", "Secours populaire"),
    ("SIAO", "SIAO"),
    ("UNAI", "UNAI"),
    ("UNEA", "UNEA"),
    ("UNAF", "Union nationale de l'aide aux familles"),
    ("UNCCAS", "Union nationale des centres communaux d'action sociale"),
    ("60000_REBONDS", "60 000 rebonds"),
    ("ADIE", "Adie"),
    ("APEC", "APEC"),
    ("APELS", "APELS Agence Pour l'Education par Le Sport"),
    ("APPRENTIS_DAUTEUIL", "Apprentis d'Auteuil"),
    ("BGE", "BGE"),
    ("CIDFF", "CIDFF"),
    ("CNAM", "CNAM"),
    ("CREPI", "CREPI"),
    ("DUO_FOR_A_JOB", "Duo for a job"),
    ("EGEE", "EGEE"),
    ("ESPACE_EMPLOI_AGRIC_ARRCO", "Espace Emploi Agirc Arrco"),
    ("FACE", "Fondation FACE"),
    ("FORCE_FEMMES", "Force Femmes"),
    ("FRANCE_ACTIVE", "France Active"),
    ("GRAND_TEST_COUVEUSE_DENTREPRISE", "Grand Test Couveuse d'entreprise"),
    ("HUP", "H'UP"),
    ("INITIATIVE_FRANCE", "Initiative France"),
    ("KONEXIO", "Konexio"),
    ("LA_CRAVATE_SOLIDAIRE", "La Cravate Solidaire"),
    ("LES_PREMIERES", "Les Premières"),
    ("LINKLUSION", "Linklusion"),
    ("NQT", "NQT"),
    ("POSITIVE_PLANET", "Positive Planet"),
    ("PROXITE", "Proxité"),
    ("RESEAU_ENTREPRENDRE", "Réseau Entreprendre"),
    ("SCCONSEIL", "SC Conseil"),
    ("SIMPLON", "Simplon"),
    ("SINCA", "SINGA"),
    ("SNC", "SNC _ Solidarité Nouvelle Face au Chômage"),
    ("SPORT_DANS_LA_VILLE", "Sport Dans La Ville"),
    ("TOUS_TES_POSSIBLE", "Tous Tes Possibles"),
    ("TZCLD", "TZCLD - Territoire Zero Chomeur Longue Durée"),
    ("UNIS_CITE", "Unis-Cité"),
    ("FEDE_PRO_FEM", "Federation Professionnelle Pour les Femmes"),
]


def structure_labels_fixture(apps, _):
    StructureLabel = apps.get_model("inclusion", "StructureLabel")
    for value, label in STRUCTURE_LABELS:
        StructureLabel.objects.create(value=value, label=label)


class Migration(migrations.Migration):
    dependencies = [
        ("inclusion", "0020_structurelabel_structurereport_accessibilite_and_more"),
    ]

    operations = [migrations.RunPython(structure_labels_fixture, migrations.RunPython.noop)]
