# Generated by Django 4.1.1 on 2022-11-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0005_enable_unaccent"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="priority_settings",
            field=models.JSONField(default=dict),
        ),
    ]
