# Generated by Django 4.1.3 on 2022-11-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0006_ds_priority_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetrow",
            name="similar_address",
            field=models.TextField(blank=True, default="", editable=False),
        ),
    ]
