# Generated by Django 4.1.3 on 2022-12-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0008_dataset_show_nearby_cnfs_permanences_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="source",
            field=models.CharField(default="", max_length=50),
        ),
    ]
