# Generated by Django 4.1.3 on 2023-02-12 17:25

from django.db import migrations, models


def migrate_data(apps, _) -> None:
    Annotation = apps.get_model("annotation", "Annotation")

    for annotation_instance in Annotation.objects.all():
        annotation_instance.dataset = annotation_instance.row.dataset
        annotation_instance.di_surrogate_id = (
            annotation_instance.row.dataset.source + "-" + annotation_instance.row.data["id"]
        )
        annotation_instance.save()


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0009_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="annotations",
                to="annotation.dataset",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="di_surrogate_id",
            field=models.TextField(null=True),
        ),
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="annotation",
            name="row",
        ),
        migrations.AlterField(
            model_name="annotation",
            name="di_surrogate_id",
            field=models.TextField(db_index=True, null=False),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="dataset",
            field=models.ForeignKey(
                on_delete=models.deletion.PROTECT,
                related_name="annotations",
                to="annotation.dataset",
            ),
        ),
        migrations.DeleteModel(
            name="DatasetRow",
        ),
    ]
