import pandas as pd
import pytest

from data_inclusion.scripts.tasks.sources import finess


@pytest.fixture
def finess_sample_df():
    return pd.DataFrame(
        [
            {
                "nofinesset": "250016987",
                "nofinessej": "250016979",
                "rs": "MAISON ACCUEIL DE LA PRAIRIE MAP",
                "rslongue": None,
                "complrs": None,
                "compldistrib": None,
                "numvoie": "8",
                "typvoie": "R",
                "voie": "JEAN BAUHIN",
                "compvoie": None,
                "lieuditbp": None,
                "commune": "388",
                "departement": "25",
                "libdepartement": "DOUBS",
                "ligneacheminement": "25200 MONTBELIARD",
                "telephone": "0399999999",
                "telecopie": None,
                "categetab": "219",
                "libcategetab": "Autre Centre d'Accueil",
                "categagretab": "4601",
                "libcategagretab": "Etablissements pour Adultes et Familles en Difficulté",
                "siret": "40999999999999",
                "codeape": "8790B",
                "codemft": "99",
                "libmft": "Indéterminé",
                "codesph": None,
                "libsph": None,
                "dateouv": "1996-06-30",
                "dateautor": "1996-06-30",
                "maj": "2011-12-26",
                "numuai": None,
                "coordxet": "986231.9",
                "coordyet": "6718959.0",
                "sourcecoordet": "1,ATLASANTE,100,IGN,BD_ADRESSE,V2.2,LAMBERT_93",
                "datemaj": "2022-07-04",
            },
            {
                "nofinesset": "970407573",
                "nofinessej": "970400222",
                "rs": "AREL",
                "rslongue": "ASSOCIATION REUNIONNAISE D'ENTRAIDE AUX LIBERES",
                "complrs": None,
                "compldistrib": None,
                "numvoie": "63",
                "typvoie": "R",
                "voie": "MONSEIGNEUR DE BEAUMONT",
                "compvoie": None,
                "lieuditbp": None,
                "commune": "411",
                "departement": "9D",
                "libdepartement": "LA REUNION",
                "ligneacheminement": "97400 ST DENIS CEDEX",
                "telephone": "0262909550",
                "telecopie": "0262415740",
                "categetab": "219",
                "libcategetab": "Autre Centre d'Accueil",
                "categagretab": "4601",
                "libcategagretab": "Etablissements pour Adultes et Familles en Difficulté",
                "siret": "32833291100036",
                "codeape": None,
                "codemft": "35",
                "libmft": "Préfet de département Subvention",
                "codesph": None,
                "libsph": None,
                "dateouv": "2009-08-10",
                "dateautor": None,
                "maj": "2016-04-05",
                "numuai": None,
                "coordxet": "339580.7",
                "coordyet": "7689972.5",
                "sourcecoordet": "1,ATLASANTE,100,IGN,BD_ADRESSE,V2.2,UTM_S40",
                "datemaj": "2022-11-04",
            },
        ]
    )


def test_transform_finess(finess_sample_df):
    df = finess.transform_structure_dataframe(finess_sample_df)

    assert df.to_dict(orient="records") == [
        {
            "id": "250016987",
            "siret": "40999999999999",
            "rna": None,
            "nom": "MAISON ACCUEIL DE LA PRAIRIE MAP",
            "commune": "MONTBELIARD",
            "code_postal": "25200",
            "code_insee": "25388",
            "adresse": "8 R JEAN BAUHIN",
            "complement_adresse": None,
            "longitude": 6.804178530803673,
            "latitude": 47.50893042700095,
            "typologie": None,
            "telephone": "0399999999",
            "courriel": None,
            "site_web": None,
            "presentation_resume": "Autre Centre d'Accueil",
            "presentation_detail": "Etablissements pour Adultes et Familles en Difficulté",
            "source": "finess",
            "date_maj": "2011-12-26T00:00:00",
            "antenne": False,
            "lien_source": None,
            "horaires_ouverture": None,
            "accessibilite": None,
            "labels_nationaux": None,
            "labels_autres": None,
            "thematiques": None,
        },
        {
            "id": "970407573",
            "siret": "32833291100036",
            "rna": None,
            "nom": "AREL",
            "commune": "ST DENIS",
            "code_postal": "97400",
            "code_insee": "97411",
            "adresse": "63 R MONSEIGNEUR DE BEAUMONT",
            "complement_adresse": None,
            "longitude": 55.45778336135475,
            "latitude": -20.88353078421472,
            "typologie": None,
            "telephone": "0262909550",
            "courriel": None,
            "site_web": None,
            "presentation_resume": "Autre Centre d'Accueil",
            "presentation_detail": "Etablissements pour Adultes et Familles en Difficulté",
            "source": "finess",
            "date_maj": "2016-04-05T00:00:00",
            "antenne": False,
            "lien_source": None,
            "horaires_ouverture": None,
            "accessibilite": None,
            "labels_nationaux": None,
            "labels_autres": None,
            "thematiques": None,
        },
    ]
