# Generated by Django 4.0.3 on 2022-07-05 17:49

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="Establishment",
            fields=[
                ("siret", models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name="Siret")),
                ("siren", models.CharField(max_length=9, verbose_name="Siren")),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("ape", models.CharField(max_length=6)),
                ("address1", models.CharField(blank=True, max_length=255)),
                ("address2", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("city_code", models.CharField(db_index=True, max_length=5)),
                ("postal_code", models.CharField(max_length=5)),
                ("is_siege", models.BooleanField()),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("full_search_text", models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name="establishment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["full_search_text"], name="full_text_trgm_idx", opclasses=("gin_trgm_ops",)
            ),
        ),
    ]
