# Generated by Django 4.0.6 on 2022-07-26 13:22

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sirene", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="establishment",
            name="full_text_trgm_idx",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="full_search_text",
        ),
        migrations.AddIndex(
            model_name="establishment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="full_text_name_trgm_idx", opclasses=("gin_trgm_ops",)
            ),
        ),
        migrations.AddIndex(
            model_name="establishment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["address1"], name="full_text_address_trgm_idx", opclasses=("gin_trgm_ops",)
            ),
        ),
    ]
