# Generated by Django 4.1.3 on 2022-11-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sirene", "0003_add_postgis"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeNAF",
            fields=[
                ("code", models.TextField(max_length=6, primary_key=True, serialize=False)),
                ("label", models.TextField()),
                ("section_code", models.TextField()),
                ("section_label", models.TextField()),
                ("division_code", models.TextField()),
                ("division_label", models.TextField()),
                ("group_code", models.TextField()),
                ("group_label", models.TextField()),
                ("class_code", models.TextField()),
                ("class_label", models.TextField()),
            ],
        ),
    ]
