# Generated by Django 4.2.1 on 2023-05-15 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sirene", "0006_alter_establishment_ape"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Establishment",
        ),
    ]
