"""init

Revision ID: 84161a5c082e
Revises:
Create Date: 2022-08-16 13:24:17.070366

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "84161a5c082e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "structure",
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Text(), nullable=True),
        sa.Column("siret", sa.Text(), nullable=True),
        sa.Column("rna", sa.Text(), nullable=True),
        sa.Column("nom", sa.Text(), nullable=True),
        sa.Column("commune", sa.Text(), nullable=True),
        sa.Column("code_postal", sa.Text(), nullable=True),
        sa.Column("code_insee", sa.Text(), nullable=True),
        sa.Column("adresse", sa.Text(), nullable=True),
        sa.Column("complement_adresse", sa.Text(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("typologie", sa.Text(), nullable=True),
        sa.Column("telephone", sa.Text(), nullable=True),
        sa.Column("courriel", sa.Text(), nullable=True),
        sa.Column("site_web", sa.Text(), nullable=True),
        sa.Column("presentation_resume", sa.Text(), nullable=True),
        sa.Column("presentation_detail", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("date_maj", sa.DateTime(timezone=True), nullable=True),
        sa.Column("structure_parente", sa.Text(), nullable=True),
        sa.Column("lien_source", sa.Text(), nullable=True),
        sa.Column("horaires_ouverture", sa.Text(), nullable=True),
        sa.Column("accessibilite", sa.Text(), nullable=True),
        sa.Column("labels_nationaux", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("labels_autres", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("index"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("structure")
    # ### end Alembic commands ###
