"""service_id_and_structure_ref

Revision ID: b9513e81ddc2
Revises: 848afea21c28
Create Date: 2022-10-06 11:05:17.991284

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b9513e81ddc2"
down_revision = "848afea21c28"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service", sa.Column("id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service", "id")
    # ### end Alembic commands ###
