"""structure_src_url

Revision ID: d36ba9e88838
Revises: e17f7cc8c271
Create Date: 2022-08-17 18:30:29.609005

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d36ba9e88838"
down_revision = "e17f7cc8c271"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("structure", sa.Column("src_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("structure", "src_url")
    # ### end Alembic commands ###
