"""structure_batch_id

Revision ID: e17f7cc8c271
Revises: 84161a5c082e
Create Date: 2022-08-16 13:25:59.579530

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e17f7cc8c271"
down_revision = "84161a5c082e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("structure", sa.Column("batch_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("structure", "batch_id")
    # ### end Alembic commands ###
