# This compose file is not suited for production. It is intended for
# development.
#
# Setting the environment should be done in the root dotenv file, to prevent
# this file from appearing as modified in git. Variables are documented in the
# dotenv file template.

version: "3.9"

services:
  api:
    image: data-inclusion-api
    build: .
    depends_on:
      - db
    restart: on-failure
    ports:
      - ${API_PORT:-8000}:8000
    environment:
      - ENV=${ENV:-dev}
      - DEBUG=${DEBUG:-False}
      - DATABASE_URL=postgresql://${POSTGRES_DB:-data_inclusion_api}:${POSTGRES_PASSWORD:-USE_IN_DEVELOPMENT_ONLY}@db:5432/${POSTGRES_DB:-data_inclusion_api}
      - SECRET_KEY=${SECRET_KEY:-USE_IN_DEVELOPMENT_ONLY}

  db:
    image: postgres:14
    restart: on-failure
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-data_inclusion_api}
      - POSTGRES_USER=${POSTGRES_USER:-data_inclusion_api}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-USE_IN_DEVELOPMENT_ONLY}
