name: api

defaults:
  run:
    working-directory: api

on:
  push:
    branches:
      - "main"
    paths:
      - "api/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "api/**"

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: up stack
        run: docker-compose up -d target-db
      - name: run tests
        run: docker-compose run --entrypoint pytest api -p no:cacheprovider -vv
