name: build_deploy_staging

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review, labeled]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'deploy-to-staging')
    uses: ./.github/workflows/_build_images.yml

