name: build_deploy_staging

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review, labeled]

jobs:
  build:
    uses: ./.github/workflows/_build_images.yml

